name: Build Wheels

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Swig (macos-latest)
        if: matrix.os == 'macos-latest'
        run: brew install swig

      - name: Install Swig (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install swig
      
      - name: Install Swig (windows-latest)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          echo Install Swig.
          curl -O https://nchc.dl.sourceforge.net/project/swig/swigwin/swigwin-4.1.1/swigwin-4.1.1.zip
          unzip swigwin-4.1.1.zip && cp swigwin-4.1.1/swig.exe /usr/bin
      
      - name: Install poetry
        shell: bash
        run: python -m pip install poetry==1.1.12

      - name: Install cibuildwheel
        shell: bash
        run: python -m pip install cibuildwheel==2.5.0

      - name: Build wheels
        shell: bash
        env:
          CIBW_ARCHS: auto
          CIBW_BUILD: cp310-*
        run: python -m cibuildwheel pkg/pypi --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
